#!/usr/bin/env node
/**
 * Download images from WordPress for MkDocs migration
 *
 * Reads the image manifest generated by convert.js, scans the converted
 * docs to determine which product uses each image, downloads them, and
 * saves to the correct product's images folder.
 *
 * Usage: node download-images.js <converted-dir> [--host https://yoursite.com]
 *
 * Arguments:
 *   converted-dir   Path to the converted output directory (from convert.js)
 *   --host URL      Production hostname to try first (rewrites EC2/dev URLs)
 */

const fs = require('fs');
const path = require('path');
const https = require('https');
const http = require('http');

// ─── Parse CLI arguments ────────────────────────────────────────────────────

const args = process.argv.slice(2);
if (args.length < 1 || args.includes('--help') || args.includes('-h')) {
  console.log(`
Usage: node download-images.js <converted-dir> [--host https://yoursite.com]

Arguments:
  converted-dir   Path to the converted output directory (from convert.js)
  --host URL      Production hostname to try first (rewrites dev/staging URLs)

Example:
  node download-images.js ./converted --host https://powerstacks.com
`);
  process.exit(args.includes('--help') || args.includes('-h') ? 0 : 1);
}

let OUTPUT_BASE = null;
let PROD_HOST = null;

for (let i = 0; i < args.length; i++) {
  if (args[i] === '--host' && args[i + 1]) {
    PROD_HOST = args[i + 1].replace(/\/$/, '');
    i++;
  } else if (!OUTPUT_BASE) {
    OUTPUT_BASE = path.resolve(args[i]);
  }
}

if (!OUTPUT_BASE) {
  console.error('Error: converted-dir argument is required');
  process.exit(1);
}

const MANIFEST_FILE = path.join(OUTPUT_BASE, 'image-manifest.txt');

if (!fs.existsSync(MANIFEST_FILE)) {
  console.error(`Error: Image manifest not found: ${MANIFEST_FILE}`);
  console.error('Run convert.js first to generate the manifest.');
  process.exit(1);
}

// Rate limit: max concurrent downloads
const MAX_CONCURRENT = 5;
const RETRY_DELAY = 2000;
const MAX_RETRIES = 2;

// ─── Read manifest ──────────────────────────────────────────────────────────

const urls = fs.readFileSync(MANIFEST_FILE, 'utf8')
  .split('\n')
  .map(u => u.trim())
  .filter(u => u.length > 0);

console.log(`Found ${urls.length} images in manifest\n`);

// ─── Scan converted docs to find which images each product uses ─────────────

const imageToProducts = {};

// Auto-detect product directories
const productSlugs = fs.readdirSync(OUTPUT_BASE, { withFileTypes: true })
  .filter(d => d.isDirectory() && fs.existsSync(path.join(OUTPUT_BASE, d.name, 'docs')))
  .map(d => d.name);

console.log(`Found product directories: ${productSlugs.join(', ')}\n`);

for (const productSlug of productSlugs) {
  const docsDir = path.join(OUTPUT_BASE, productSlug, 'docs');
  if (!fs.existsSync(docsDir)) continue;

  const scanDir = (dir) => {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory() && entry.name !== 'images') {
        scanDir(fullPath);
      } else if (entry.isFile() && entry.name.endsWith('.md')) {
        const content = fs.readFileSync(fullPath, 'utf8');
        const imgRefs = content.matchAll(/!\[[^\]]*\]\((?:\.\.\/)?images\/([^)]+)\)/g);
        for (const match of imgRefs) {
          const filename = match[1];
          if (!imageToProducts[filename]) imageToProducts[filename] = new Set();
          imageToProducts[filename].add(productSlug);
        }
      }
    }
  };
  scanDir(docsDir);
}

console.log(`Found ${Object.keys(imageToProducts).length} unique image filenames referenced in docs\n`);

// ─── Build download list ────────────────────────────────────────────────────

const downloadList = [];

for (const originalUrl of urls) {
  const filenameMatch = originalUrl.match(/\/([^/?]+\.(png|jpg|jpeg|gif|webp|svg))(\?.*)?$/i);
  if (!filenameMatch) continue;
  const filename = filenameMatch[1];

  // Get the path portion after the host for production URL rewriting
  const pathMatch = originalUrl.match(/\/wordpress(\/wp-content\/uploads\/.+)$/i)
    || originalUrl.match(/(\/wp-content\/uploads\/.+)$/i);
  const urlPath = pathMatch ? pathMatch[1] : null;

  const products = imageToProducts[filename];
  if (!products || products.size === 0) {
    continue;
  }

  // Build the production URL if --host was provided
  const prodUrl = (PROD_HOST && urlPath) ? `${PROD_HOST}${urlPath}` : null;

  downloadList.push({
    filename,
    prodUrl,
    originalUrl,
    products: Array.from(products),
  });
}

console.log(`${downloadList.length} images to download (referenced by docs)`);
console.log(`Skipping ${urls.length - downloadList.length} images not referenced by any converted doc\n`);

// ─── Download function ──────────────────────────────────────────────────────

function downloadFile(url, destPath, retries = 0) {
  return new Promise((resolve, reject) => {
    const client = url.startsWith('https') ? https : http;

    const req = client.get(url, { timeout: 15000 }, (res) => {
      // Handle redirects
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        downloadFile(res.headers.location, destPath, retries).then(resolve).catch(reject);
        return;
      }

      if (res.statusCode !== 200) {
        res.resume();
        reject(new Error(`HTTP ${res.statusCode}`));
        return;
      }

      const fileStream = fs.createWriteStream(destPath);
      res.pipe(fileStream);
      fileStream.on('finish', () => {
        fileStream.close();
        resolve(true);
      });
      fileStream.on('error', reject);
    });

    req.on('error', reject);
    req.on('timeout', () => {
      req.destroy();
      reject(new Error('Timeout'));
    });
  });
}

async function downloadWithFallback(item) {
  const { filename, prodUrl, originalUrl, products } = item;

  const destPaths = products.map(p =>
    path.join(OUTPUT_BASE, p, 'docs', 'images', filename)
  );

  for (const destPath of destPaths) {
    fs.mkdirSync(path.dirname(destPath), { recursive: true });
  }

  const primaryDest = destPaths[0];

  const urlsToTry = [];
  if (prodUrl) urlsToTry.push(prodUrl);
  urlsToTry.push(originalUrl);

  let success = false;
  let lastError = null;

  for (const url of urlsToTry) {
    for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
      try {
        await downloadFile(url, primaryDest);
        success = true;
        break;
      } catch (err) {
        lastError = err;
        if (attempt < MAX_RETRIES) {
          await new Promise(r => setTimeout(r, RETRY_DELAY));
        }
      }
    }
    if (success) break;
  }

  if (!success) {
    return { filename, success: false, error: lastError.message };
  }

  // Copy to other product folders
  for (let i = 1; i < destPaths.length; i++) {
    fs.copyFileSync(primaryDest, destPaths[i]);
  }

  return { filename, success: true, products };
}

// ─── Run downloads with concurrency limit ───────────────────────────────────

async function main() {
  const results = { success: 0, failed: 0, failedFiles: [] };
  let completed = 0;

  for (let i = 0; i < downloadList.length; i += MAX_CONCURRENT) {
    const batch = downloadList.slice(i, i + MAX_CONCURRENT);
    const batchResults = await Promise.all(batch.map(downloadWithFallback));

    for (const result of batchResults) {
      completed++;
      if (result.success) {
        results.success++;
        process.stdout.write(`  [${completed}/${downloadList.length}] + ${result.filename}\n`);
      } else {
        results.failed++;
        results.failedFiles.push({ file: result.filename, error: result.error });
        process.stdout.write(`  [${completed}/${downloadList.length}] x ${result.filename} -- ${result.error}\n`);
      }
    }
  }

  console.log(`\n${'='.repeat(60)}`);
  console.log('  DOWNLOAD COMPLETE');
  console.log(`${'='.repeat(60)}`);
  console.log(`  Downloaded: ${results.success}`);
  console.log(`  Failed:     ${results.failed}`);

  if (results.failedFiles.length > 0) {
    console.log('\n  Failed files:');
    for (const f of results.failedFiles) {
      console.log(`    ${f.file} -- ${f.error}`);
    }

    const failedManifest = results.failedFiles.map(f => {
      const item = downloadList.find(d => d.filename === f.file);
      return `${f.file}\n  prod: ${item.prodUrl || 'N/A'}\n  orig: ${item.originalUrl}`;
    }).join('\n\n');
    fs.writeFileSync(path.join(OUTPUT_BASE, 'failed-images.txt'), failedManifest, 'utf8');
    console.log(`\n  Failed URLs saved to: ${path.join(OUTPUT_BASE, 'failed-images.txt')}`);
  }

  console.log('');
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
